export default function AIUsage() {
  return (
    <section className="rounded-xl border border-[#B4C2D1]/70 bg-white p-6 shadow-sm">
      <div className="mb-5">
        <p className="text-xs font-bold uppercase tracking-[0.16em] text-[#E26D5C]">
          AI USAGE
        </p>

        <h2 className="mt-1 text-xl font-black uppercase text-[#082550]">
          Usage & Monitoring
        </h2>

        <p className="mt-2 text-sm leading-6 text-[#272D2C]/65">
          The future location for monitoring AI activity, usage, and
          operational limits across the CascadEffects platform.
        </p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <UsageCard
          label="AI Requests"
          value="—"
          description="Requests will appear here once an AI provider is connected."
        />

        <UsageCard
          label="Tokens Used"
          value="—"
          description="Token consumption will be tracked after AI integration is enabled."
        />

        <UsageCard
          label="Estimated Cost"
          value="—"
          description="Future usage reporting may provide visibility into AI service costs."
        />

        <UsageCard
          label="Usage Limit"
          value="Not configured"
          description="Future administrators may define platform-level AI usage controls."
        />
      </div>

      <div className="mt-5 rounded-lg border border-dashed border-[#B4C2D1] bg-[#F7F9FB] p-4">
        <p className="text-[10px] font-black uppercase tracking-[0.14em] text-[#082550]">
          MONITORING PREVIEW
        </p>

        <p className="mt-1 text-xs leading-5 text-[#272D2C]/60">
          Usage information is intentionally unavailable while AI provider
          integration is disabled. No AI requests or costs are being
          generated by this preview page.
        </p>
      </div>
    </section>
  );
}

function UsageCard({
  label,
  value,
  description,
}: {
  label: string;
  value: string;
  description: string;
}) {
  return (
    <div className="rounded-lg border border-[#B4C2D1]/60 bg-[#F7F9FB] p-4">
      <p className="text-[10px] font-black uppercase tracking-[0.14em] text-[#272D2C]/55">
        {label}
      </p>

      <p className="mt-2 text-lg font-black text-[#082550]">{value}</p>

      <p className="mt-2 text-xs leading-5 text-[#272D2C]/60">
        {description}
      </p>
    </div>
  );
}