import { supabase } from "@/lib/supabase/client";

import type {
  BuilderDocument,
} from "@/lib/types/builderdocument";

/* ==========================================================
   Types
========================================================== */

export type PerformanceSheetStatus =
  | "draft"
  | "published"
  | "archived";

export interface PerformanceSheetRecord {
  id: string;

  organization_id: string;

  sheet_key: string;

  name: string;

  status: PerformanceSheetStatus;

  version: number;

  document: BuilderDocument;

  created_at: string;

  updated_at: string;
}

/* ==========================================================
   Save Builder Document
========================================================== */

export async function saveBuilderDocument(
  organizationId: string,
  document: BuilderDocument,
  sheetId?: string
): Promise<PerformanceSheetRecord> {
  /*
   * Existing sheet:
   * only drafts may be edited.
   */
  if (sheetId) {
    const { data, error } = await supabase
      .from("performance_sheets")
      .update({
        document,
      })
      .eq(
        "id",
        sheetId
      )
      .eq(
        "organization_id",
        organizationId
      )
      .eq(
        "status",
        "draft"
      )
      .select()
      .single();

    if (error) {
      throw new Error(
        `Failed to save performance sheet: ${error.message}`
      );
    }

    return data as PerformanceSheetRecord;
  }

  /*
   * No sheet exists yet.
   *
   * Create Version 1 of a new logical
   * performance sheet.
   *
   * sheet_key is generated by PostgreSQL.
   */
  const { data, error } = await supabase
    .from("performance_sheets")
    .insert({
      organization_id:
        organizationId,

      name:
        "Performance Sheet",

      status:
        "draft",

      version:
        1,

      document,
    })
    .select()
    .single();

  if (error) {
    throw new Error(
      `Failed to create performance sheet: ${error.message}`
    );
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Load Builder Document
========================================================== */

export async function loadBuilderDocument(
  organizationId: string,
  sheetId: string
): Promise<PerformanceSheetRecord> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "id",
      sheetId
    )
    .eq(
      "organization_id",
      organizationId
    )
    .single();

  if (error) {
    throw new Error(
      `Failed to load performance sheet: ${error.message}`
    );
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Load Latest Draft
========================================================== */

export async function loadLatestDraft(
  organizationId: string
): Promise<PerformanceSheetRecord | null> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "draft"
    )
    .order(
      "updated_at",
      {
        ascending: false,
      }
    )
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to load draft performance sheet: ${error.message}`
    );
  }

  if (!data) {
    return null;
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Publish Performance Sheet
========================================================== */

export async function publishPerformanceSheet(
  organizationId: string,
  sheetId: string
): Promise<PerformanceSheetRecord> {
  /*
   * Only a draft can become published.
   *
   * Once published, saveBuilderDocument()
   * will no longer update this row because
   * that function explicitly requires
   * status = draft.
   */
  const { data, error } = await supabase
    .from("performance_sheets")
    .update({
      status:
        "published",
    })
    .eq(
      "id",
      sheetId
    )
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "draft"
    )
    .select()
    .single();

  if (error) {
    throw new Error(
      `Failed to publish performance sheet: ${error.message}`
    );
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Create Draft Revision
========================================================== */

export async function createDraftRevision(
  organizationId: string,
  publishedSheetId: string
): Promise<PerformanceSheetRecord> {
  /*
   * Load the published version that will
   * become the basis of the new revision.
   */
  const {
    data: publishedSheet,
    error: loadError,
  } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "id",
      publishedSheetId
    )
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "published"
    )
    .single();

  if (loadError) {
    throw new Error(
      `Failed to load published performance sheet: ${loadError.message}`
    );
  }

  const source =
    publishedSheet as PerformanceSheetRecord;

  /*
   * Find the highest existing version for
   * this logical performance sheet.
   *
   * We do not assume source.version + 1,
   * because additional historical versions
   * may already exist.
   */
  const {
    data: latestVersion,
    error: versionError,
  } = await supabase
    .from("performance_sheets")
    .select(
      "version"
    )
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "sheet_key",
      source.sheet_key
    )
    .order(
      "version",
      {
        ascending: false,
      }
    )
    .limit(1)
    .single();

  if (versionError) {
    throw new Error(
      `Failed to determine next performance sheet version: ${versionError.message}`
    );
  }

  const nextVersion =
    latestVersion.version + 1;

  /*
   * Create a new draft row.
   *
   * Same sheet_key:
   * same logical performance sheet.
   *
   * New id:
   * new immutable version.
   */
  const { data, error } = await supabase
    .from("performance_sheets")
    .insert({
      organization_id:
        organizationId,

      sheet_key:
        source.sheet_key,

      name:
        source.name,

      status:
        "draft",

      version:
        nextVersion,

      document:
        source.document,
    })
    .select()
    .single();

  if (error) {
    throw new Error(
      `Failed to create draft revision: ${error.message}`
    );
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Load Latest Published Version
   ----------------------------------------------------------
   Used when we already know the logical sheet_key.
========================================================== */

export async function loadLatestPublished(
  organizationId: string,
  sheetKey: string
): Promise<PerformanceSheetRecord | null> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "sheet_key",
      sheetKey
    )
    .eq(
      "status",
      "published"
    )
    .order(
      "version",
      {
        ascending: false,
      }
    )
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to load published performance sheet: ${error.message}`
    );
  }

  if (!data) {
    return null;
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   Load Latest Published For Organization
   ----------------------------------------------------------
   Used during Builder startup when there is no draft
   and we do not yet know the logical sheet_key.

   Current Builder v1 assumes one active logical
   performance sheet per organization.

   When the platform supports a library of multiple
   performance sheet definitions, startup will load
   by selected sheet_key instead.
========================================================== */

export async function loadLatestPublishedForOrganization(
  organizationId: string
): Promise<PerformanceSheetRecord | null> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "published"
    )
    .order(
      "updated_at",
      {
        ascending: false,
      }
    )
    .limit(1)
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to load published performance sheet: ${error.message}`
    );
  }

  if (!data) {
    return null;
  }

  return data as PerformanceSheetRecord;
}

/* ==========================================================
   List Performance Sheet Definitions
   ----------------------------------------------------------
   Returns the latest version of each logical Performance
   Sheet definition for an organization.

   A logical Performance Sheet is identified by sheet_key.

   Example:

   sheet_key = annual-performance
   version   = 1
   version   = 2
   version   = 3

   Administration should treat these as one logical
   Performance Sheet definition.

   The latest version is returned as the management
   entry point while historical versions remain preserved
   in the database.
========================================================== */

export async function listPerformanceSheetDefinitions(
  organizationId: string
): Promise<PerformanceSheetRecord[]> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .order(
      "sheet_key",
      {
        ascending: true,
      }
    )
    .order(
      "version",
      {
        ascending: false,
      }
    );

  if (error) {
    throw new Error(
      `Failed to load performance sheet definitions: ${error.message}`
    );
  }

  const records =
    (data ?? []) as PerformanceSheetRecord[];

  /*
   * Because records are ordered by:
   *
   * sheet_key ASC
   * version DESC
   *
   * the first record encountered for
   * each sheet_key is the highest version.
   */
  const latestBySheetKey =
    new Map<
      string,
      PerformanceSheetRecord
    >();

  for (const record of records) {
    if (
      !latestBySheetKey.has(
        record.sheet_key
      )
    ) {
      latestBySheetKey.set(
        record.sheet_key,
        record
      );
    }
  }

  return Array.from(
    latestBySheetKey.values()
  );
}

/* ==========================================================
   Find Performance Sheet Versions
   ----------------------------------------------------------
   Returns all preserved versions belonging to the same
   logical Performance Sheet definition.

   Versions are returned from newest to oldest.
========================================================== */

export async function findPerformanceSheetVersions(
  organizationId: string,
  sheetKey: string
): Promise<PerformanceSheetRecord[]> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "sheet_key",
      sheetKey
    )
    .order(
      "version",
      {
        ascending: false,
      }
    );

  if (error) {
    throw new Error(
      `Failed to load performance sheet versions: ${error.message}`
    );
  }

  return (
    (data ?? []) as PerformanceSheetRecord[]
  );
}

/* ==========================================================
   Find Published Performance Sheets By Organization
   ----------------------------------------------------------
   Used by Administration Assignment Management.

   Assignments may only reference exact published
   Performance Sheet versions.

   Draft and archived versions are intentionally excluded.
========================================================== */

export async function findPublishedPerformanceSheetsByOrganization(
  organizationId: string
): Promise<PerformanceSheetRecord[]> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "published"
    )
    .order(
      "name",
      {
        ascending: true,
      }
    )
    .order(
      "version",
      {
        ascending: false,
      }
    );

  if (error) {
    throw new Error(
      `Failed to load published performance sheets: ${error.message}`
    );
  }

  return (
    (data ?? []) as PerformanceSheetRecord[]
  );
}

/* ==========================================================
   Load Published Performance Sheet By Id
   ----------------------------------------------------------
   Used by Runtime execution when an Assignment references
   a specific published Performance Sheet version.
========================================================== */

export async function loadPublishedById(
  organizationId: string,
  performanceSheetId: string
): Promise<PerformanceSheetRecord | null> {
  const { data, error } = await supabase
    .from("performance_sheets")
    .select("*")
    .eq(
      "id",
      performanceSheetId
    )
    .eq(
      "organization_id",
      organizationId
    )
    .eq(
      "status",
      "published"
    )
    .maybeSingle();

  if (error) {
    throw new Error(
      `Failed to load published performance sheet: ${error.message}`
    );
  }

  if (!data) {
    return null;
  }

  return data as PerformanceSheetRecord;
}